### ISSUE TITLE
Sjablonen

### ISSUE THREAD

**Issue by YaimoCollins** [lo7e-amo2-2/Project#1]

**Comment by YaimoCollins** [comment]
[Project template.docx](https://github.com/lo7e-amo2-2/Project/files/2836552/Project.template.docx)

**Comment by AranShirwani** [comment]
[Sjabloon_template.docx](https://github.com/lo7e-amo2-2/Project/files/2836553/Sjabloon_template.docx)

**Comment by Nixel1324** [comment]
[Project template Jeroen.docx](https://github.com/lo7e-amo2-2/Project/files/2836557/Project.template.Jeroen.docx)
